# Generated by Django 3.1.3 on 2020-11-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('email_from', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(null=True)),
                ('body', models.CharField(blank=True, max_length=5000)),
                ('attachment', models.CharField(blank=True, max_length=1000)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_email.email')),
            ],
        ),
    ]
