# Generated by Django 3.1.3 on 2020-11-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email_id',
            new_name='email',
        ),
    ]
